image:
  name: qmkfm/qmk_cli

stages:
  - build

build:
  stage: build
  script:
    - qmk setup --yes
    - qmk compile qmk-config.json
    - cp /qmk_firmware/*.hex .
  artifacts:
      paths:
      - "*.hex"
      expire_in: never
  only:
    changes:
      - "qmk-config.json"
